name: Build & Publish to PyPI using cibuildwheel

on:
  push:
    tags:
      - "*"

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist

  publish-wheels:
    needs: build-wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Allow the action to write to the repository
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
